<script lang="ts">
	import Section from '$lib/components/Section.svelte';
	import CodeBlock from '$lib/components/CodeBlock.svelte';

	const instrumentSig = `module Instrument : sig
  type t
  type id = Id of string
  type asset_class = Equity | Future | Option | Currency

  val create : id -> asset_class -> exchange:string -> t
  val id : t -> id
  val asset_class : t -> asset_class
  val dependencies : t -> id list
end`;

	const bookSig = `module OrderBook : sig
  type t
  type side = Bid | Ask
  type level = { price : Decimal.t; quantity : int }

  val empty : t
  val apply : t -> MarketEvent.t -> t
  val best_bid : t -> level option
  val best_ask : t -> level option
  val spread : t -> Decimal.t option
end`;

	const riskSig = `module RiskGateway : sig
  type t
  type order = { instrument : Instrument.id; side : side; qty : int; price : Decimal.t }
  type violation = NotionalLimit | PositionLimit | DuplicateOrder

  val create : limits:LimitConfig.t -> t
  val validate : t -> order -> (unit, violation list) result
end`;
</script>

<svelte:head>
	<title>Architecture — QuantSlate</title>
	<meta name="description" content="Explore the architecture of the QuantSlate trading engine." />
</svelte:head>

<Section class="prose-custom">
	<h1>System Architecture</h1>

	<p class="text-lg text-neutral-600 leading-relaxed">
		QuantSlate is structured as a modular, event-driven system. Each component is designed to be 
		testable in isolation, with well-defined interfaces that mirror the boundaries of real trading infrastructure.
	</p>

	<h2>High-Level Design</h2>
	<p>
		The engine follows a pipeline architecture. Market data flows in from the Zerodha Kite adapter, is normalized into 
		a unified domain model, and then consumed by the strategy engine. Orders generated by strategies pass through 
		a risk gateway before being converted into paper-trading executions.
	</p>

	<h2>Core Components</h2>

	<h3>1. Market Data Adapter</h3>
	<p>
		The adapter layer abstracts away the specifics of the Zerodha Kite Connect API. It handles WebSocket reconnections, 
		tick normalization, and schema versioning. All downstream components speak a single, broker-agnostic language.
	</p>

	<h3>2. Normalized Order Book</h3>
	<p>
		Market events are folded into an immutable order book data structure. By representing the book as a persistent 
		data structure, we can efficiently snapshot state at any point in time — a critical capability for backtesting and audit.
	</p>
	<CodeBlock code={bookSig} language="ocaml" />

	<h3>3. Securities Database (SecDB)</h3>
	<p>
		Inspired by Goldman Sachs' SecDB, our instrument store treats every tradable entity as a node in a dependency graph. 
		Futures depend on their underlying spot. Options depend on volatility surfaces. This graph structure allows risk 
		to propagate naturally through the system.
	</p>
	<CodeBlock code={instrumentSig} language="ocaml" />

	<h3>4. Order Management System (OMS)</h3>
	<p>
		The OMS is the single source of truth for all order lifecycle events. It tracks states from creation through 
		pending, open, partially filled, and closed. Every transition is logged immutably to an append-only event store.
	</p>

	<h3>5. Risk Gateway</h3>
	<p>
		Before any order reaches the market (even a simulated one), it must pass through the risk gateway. 
		We enforce pre-trade checks including notional limits, position concentration limits, and duplicate order detection.
	</p>
	<CodeBlock code={riskSig} language="ocaml" />

	<h3>6. Strategy Engine</h3>
	<p>
		Strategies are implemented as pure functions over market state. They receive a read-only view of the book 
		and the SecDB, and emit a stream of intended actions. This functional design makes strategies trivial to test 
		against historical data.
	</p>

	<h3>7. Execution & Simulation</h3>
	<p>
		In educational mode, the execution layer simulates fills based on market impact models and historical liquidity profiles. 
		This allows us to evaluate strategy performance without exposing capital to market risk.
	</p>

	<h2>Data Flow</h2>
	<p>
		The flow is intentionally unidirectional: <strong>Market Data → Normalization → Book → Strategy → Risk → OMS → Execution.</strong> 
		Feedback loops (such as fill reports updating position state) are handled through explicit event channels rather than 
		implicit mutable state, keeping the data flow transparent and replayable.
	</p>
</Section>
